spring.application.name=fipiran-api
# Server
server.port=9001
server.servlet.context-path=/fipiran
# External APIs
external.fipiran.base-url=https://www.fipiran.ir
external.fipiran.user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
external.fipiran.referer=https://www.fipiran.ir/
external.fipiran.origin=https://www.fipiran.ir
# Logging
logging.level.com.ernoxin=DEBUG
# =========================
# Virtual Threads (Java 21 / Project Loom)
# =========================
spring.threads.virtual.enabled=true
# =========================
# Tomcat Tuning
# =========================
server.tomcat.max-connections=8192
server.tomcat.accept-count=100
server.tomcat.connection-timeout=5s
