server.port=9001
server.servlet.context-path=/fipiran
external.fipiran.base-url=https://www.fipiran.ir
external.fipiran.user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
external.fipiran.referer=https://www.fipiran.ir/
external.fipiran.origin=https://www.fipiran.ir